# Generated by Django 3.2.3 on 2023-07-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_remove_ingredient_unique_name_measurement_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
