# Generated by Django 3.2.3 on 2023-07-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230706_1144'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
